In [145]:
import numpy as np

In [146]:
# Create array from 0 to 5 and print data type
arr = np.array([0, 1, 2, 3, 4, 5])
print(arr.dtype)

int32


In [147]:
# 2. Check if dtype is float64
arr = np.array([1.0, 2.0, 3.0])
print(arr.dtype == np.float64)

True


In [148]:
# 3. Create complex128 array
arr = np.array([1+2j, 3+4j, 5+6j], dtype=np.complex128)
print(arr)

[1.+2.j 3.+4.j 5.+6.j]


In [149]:
# 4. Convert int array to float32
arr = np.array([1, 2, 3])
arr = arr.astype(np.float32)
print(arr.dtype)

float32


In [150]:
# 5. Convert float64 to float32
arr = np.array([1.1, 2.2, 3.3], dtype=np.float64)
arr = arr.astype(np.float32)
print(arr.dtype)


float32


In [151]:
# 6. Return shape, size, dtype
def array_attributes(a):
    return a.shape, a.size, a.dtype

In [152]:
# 7. Return dimensions of array
def array_dimension(a):
    return a.ndim

In [153]:
# 8. Return item size and total bytes
def item_size_info(a):
    return a.itemsize, a.nbytes

In [154]:
# 9. Return array strides
def array_strides(a):
    return a.strides

In [155]:
# 10. Return shape and strides
def shape_stride_relationship(a):
    return a.shape, a.strides


In [156]:
# 11. Create zeros array with n elements
def create_zeros_array(n):
    return np.zeros(n)

In [157]:
# 12. Create 2D ones matrix
def create_ones_matrix(rows, cols):
    return np.ones((rows, cols))

In [158]:
# 13. Generate array using range
def generate_range_array(start, stop, step):
    return np.arange(start, stop, step)

In [159]:
# 14. Generate linear spaced array
def generate_linear_space(start, stop, num):
    return np.linspace(start, stop, num)

In [160]:
# 15. Identity matrix using eye
def create_identity_matrix(n):
    return np.eye(n)


In [161]:
# 16. Convert list to numpy array
def list_to_array(lst):
    return np.array(lst)


In [162]:
# 17. Create a view of numpy array
a = np.array([1, 2, 3, 4])
b = a.view()
print(b)

[1 2 3 4]


In [163]:
# 18. Concatenate two arrays along axis
def concatenate_arrays(a1, a2, axis):
    return np.concatenate((a1, a2), axis=axis)

In [164]:
# 19. Concatenate arrays with different shapes
x = np.array([[1, 2], [3, 4]])
y = np.array([[5], [6]])
print(np.concatenate((x, y), axis=1))

[[1 2 5]
 [3 4 6]]


In [165]:
# 20. Vertically stack arrays
arr_list = [np.array([1, 2]), np.array([3, 4])]
print(np.vstack(arr_list))

[[1 2]
 [3 4]]


In [166]:
# 21. Generate array in range with step
def generate_range(start, end, step):
    return np.arange(start, end + 1, step)

In [167]:
# 22. 10 equally spaced values from 0 to 1
print(np.linspace(0, 1, 10))


[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [168]:
# 23. Logarithmic spacing between 1 and 1000
print(np.logspace(0, 3, 5))


[   1.            5.62341325   31.6227766   177.827941   1000.        ]


In [169]:
# 24. Create DataFrame from NumPy array
import pandas as pd
data = np.random.randint(1, 101, size=(5, 3))
df = pd.DataFrame(data)
print(df)

    0   1   2
0  25  31  32
1   3  27  66
2  80  60  79
3  39  12  86
4  62  87  95


In [170]:
# 25. Replace negative values with 0
def replace_negatives_with_zero(arr):
    arr[arr < 0] = 0
    return arr

In [171]:
# 26. Access 3rd element from array
arr = np.array([10, 20, 30, 40])
print(arr[2])

30


In [172]:
# 27. Access element at (1, 2)
arr2d = np.array([[1, 2, 3], [4, 5, 6]])
print(arr2d[1, 2])


6


In [173]:
# 28. Elements greater than 5
arr = np.array([1, 6, 8, 3])
print(arr[arr > 5])


[6 8]


In [174]:
# 29. Slice index 2 to 5 inclusive
arr = np.array([0, 1, 2, 3, 4, 5, 6])
print(arr[2:6])

[2 3 4 5]


In [175]:
# 30. Slice sub-array [[2, 3], [5, 6]]
arr2d = np.array([[1, 2, 3], [4, 5, 6]])
print(arr2d[:, 1:])

[[2 3]
 [5 6]]


In [176]:
# 31. Extract elements using indices
arr = np.array([[10, 20], [30, 40]])
indices = [0, 1]
print(arr[indices, indices])

[10 40]


In [177]:
# 32. Filter elements > threshold
arr = np.array([1, 10, 5, 8])
print(arr[arr > 5])


[10  8]


In [178]:
# 33. Specific elements from 3D using index arrays
arr3d = np.arange(27).reshape(3, 3, 3)
print(arr3d[[0, 1], [1, 2], [2, 0]])

[ 5 15]


In [179]:
# 34. Elements satisfying two conditions
arr = np.array([2, 7, 5, 10])
print(arr[(arr > 3) & (arr < 9)])

[7 5]


In [180]:
# 35. Extract from 2D using row and col indices
arr2d = np.array([[10, 20, 30], [40, 50, 60]])
rows = [0, 1]
cols = [1, 2]
print(arr2d[rows, cols])

[20 60]


In [181]:
# 36. Add 5 using broadcasting
arr = np.array([1, 2, 3])
print(arr + 5)

[6 7 8]


In [182]:
# 37. Multiply each row with elements of (1, 3)
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
b = np.array([[1, 2, 3]])
print(a * b)

[[ 1  4  9]
 [ 4 10 18]
 [ 7 16 27]]


In [183]:
# 38. Add (1, 4) to each row of (4, 3)
a = np.ones((4, 3))
b = np.array([[1, 2, 3]])
print(a + b)

[[2. 3. 4.]
 [2. 3. 4.]
 [2. 3. 4.]
 [2. 3. 4.]]


In [184]:
# 39. Add (3, 1) and (1, 3)
a = np.ones((3, 1))
b = np.ones((1, 3))
print(a + b)

[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]


In [185]:
# 40. Handle incompatible shape multiplication
a = np.ones((2, 3))
b = np.ones((2, 2))
try:
    print(a * b)
except ValueError as e:
    print(e)

operands could not be broadcast together with shapes (2,3) (2,2) 


In [186]:
# 41. Column-wise mean
arr = np.array([[1, 2], [3, 4]])
print(arr.mean(axis=0))

[2. 3.]


In [187]:
# 42. Max in each row
print(arr.max(axis=1))

[2 4]


In [188]:
# 43. Indices of max in each col
print(arr.argmax(axis=0))

[1 1]


In [189]:
# 44. Moving sum along rows
def moving_sum(arr):
    return np.cumsum(arr, axis=1)
print(moving_sum(np.array([[1, 2], [3, 4]])))

[[1 3]
 [3 7]]


In [190]:
# 45. Check all elements even in each col
arr = np.array([[2, 4], [6, 8]])
print(np.all(arr % 2 == 0, axis=0))

[ True  True]


In [191]:
# 46. Reshape to m x n
arr = np.arange(12)
print(arr.reshape(3, 4))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [192]:
# 47. Flatten matrix
arr2d = np.array([[1, 2], [3, 4]])
print(arr2d.flatten())

[1 2 3 4]


In [193]:
# 48. Concatenate along axis
arr1 = np.array([[1, 2]])
arr2 = np.array([[3, 4]])
print(np.concatenate((arr1, arr2), axis=0))

[[1 2]
 [3 4]]


In [194]:
# 49. Split array into sub-arrays
arr = np.array([1, 2, 3, 4, 5, 6])
print(np.split(arr, 3))

[array([1, 2]), array([3, 4]), array([5, 6])]


In [195]:
# 50. Insert and delete elements
arr = np.array([1, 2, 3])
arr = np.insert(arr, 1, 10)
arr = np.delete(arr, 2)
print(arr)

[ 1 10  3]


In [196]:
# 51. Element-wise addition
arr1 = np.array([1, 2])
arr2 = np.array([3, 4])
print(arr1 + arr2)

[4 6]


In [197]:
# 52. Element-wise subtraction
print(arr1 - arr2)

[-2 -2]


In [198]:
# 53. Element-wise multiplication
print(arr1 * arr2)

[3 8]


In [199]:
# 54. Element-wise division
print(arr1 / arr2)


[0.33333333 0.5       ]


In [200]:
# 55. Element-wise exponentiation
print(arr1 ** arr2)

[ 1 16]


In [201]:
# 56. Count substring 'a'
arr = np.array(['apple', 'banana', 'grape'])
print(np.char.count(arr, 'a'))

[1 3 1]


In [202]:
# 57. Extract uppercase
arr = np.array(['AbC', 'Def'])
print(np.char.upper(arr))

['ABC' 'DEF']


In [203]:
# 58. Replace substring
print(np.char.replace(arr, 'a', '*'))

['AbC' 'Def']


In [204]:
# 59. Concatenate strings element-wise
arr1 = np.array(['hello', 'world'])
arr2 = np.array(['123', '456'])
print(np.char.add(arr1, arr2))

['hello123' 'world456']


In [205]:
# 60. Length of longest string
print(max(np.char.str_len(arr)))

3


In [206]:
# 61. Random 100 ints and stats
arr = np.random.randint(1, 1001, 100)
print(np.mean(arr), np.median(arr), np.var(arr), np.std(arr))

484.13 516.0 88777.55309999999 297.95562270244204


In [207]:
# 62. 25th and 75th percentiles
arr = np.random.randint(1, 101, 50)
print(np.percentile(arr, [25, 75]))


[42.25 75.  ]


In [208]:
# 63. Correlation coefficient
x = np.array([1, 2, 3])
y = np.array([2, 4, 6])
print(np.corrcoef(x, y))

[[1. 1.]
 [1. 1.]]


In [209]:
# 64. Matrix multiplication
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
print(np.dot(a, b))

[[19 22]
 [43 50]]


In [210]:
# 65. Percentiles and quartiles
arr = np.random.randint(1, 101, 50)
print(np.percentile(arr, [10, 50, 90]))

[14.7 54.5 88.8]


In [211]:
# 66. Index of specific element
arr = np.array([10, 20, 30, 40])
print(np.where(arr == 30))

(array([2], dtype=int64),)


In [212]:
# 67. Sort array ascending
arr = np.random.randint(1, 100, 10)
print(np.sort(arr))

[13 26 32 48 51 64 80 85 94 99]


In [213]:
# 68. Filter > 20
print(arr[arr > 20])

[32 64 99 85 94 51 48 80 26]


In [214]:
# 69. Elements divisible by 3
print(arr[arr % 3 == 0])

[99 51 48]


In [215]:
# 70. Elements between 20 and 40
print(arr[(arr >= 20) & (arr <= 40)])

[32 26]
